import { CATALOGO,bornes } from '../modelo/catalogo';
import type { Projeto, TipoLigacao } from '../modelo/tipos';
import { tipoCompativel } from '../modelo/operacoes';
import { IconeOficina } from './IconeOficina';
export function InspetorOficina({projeto,selecionado,ligada,livre,origem,alterar,terminal,remover}:{projeto:Projeto;selecionado:string|null;ligada:boolean;livre:boolean;origem:string|null;alterar:(p:Projeto)=>void;terminal:(id:string)=>void;remover:()=>void}) {
 const p=projeto.pecas.find(p=>p.id===selecionado),l=projeto.ligacoes.find(l=>l.id===selecionado);
 function editarPeca(campos:Partial<NonNullable<typeof p>>){alterar({...projeto,pecas:projeto.pecas.map(c=>c.id===p?.id?{...c,...campos}:c)});}
 function editarLigacao(campos:Partial<NonNullable<typeof l>>){alterar({...projeto,ligacoes:projeto.ligacoes.map(c=>c.id===l?.id?{...c,...campos}:c)});}
 return <section className="of-inspetor" aria-label="Inspeção"><div className="of-cabecalho-painel"><span>03 / INSPEÇÃO</span><IconeOficina nome="sonda"/></div>{p?<><div className="of-identificacao"><b>{p.tag}</b><span>{CATALOGO[p.tipo].nome}</span></div><p>{CATALOGO[p.tipo].descricao}</p><div className="of-bornes" aria-label={`Bornes de ${p.tag}`}>{bornes(p).map(b=>{const id=`${p.id}:${b}`;return <button key={b} aria-pressed={origem===id} onClick={()=>terminal(id)} aria-label={`Borne ${p.tag}.${b}`}><i/>{b}</button>;})}</div>
 {livre&&<label className="of-campo">Identificação<input aria-label="Identificação da peça" key={`${p.id}-${p.tag}`} defaultValue={p.tag} maxLength={12} disabled={ligada} onBlur={e=>{const tag=e.target.value.trim().toUpperCase();if(/^[A-Z][A-Z0-9_-]{0,11}$/.test(tag)&&!projeto.pecas.some(c=>c.id!==p.id&&c.tag===tag)){if(tag!==p.tag)editarPeca({tag});}else e.target.value=p.tag;}}/></label>}
 {['motor','engrenagem','polia','rolete'].includes(p.tipo)&&<label className="of-campo">{p.tipo==='motor'?'Rotação livre (rpm)':p.tipo==='engrenagem'?'Número de dentes':'Diâmetro (mm)'}<input aria-label={p.tipo==='motor'?'Rotação livre':p.tipo==='engrenagem'?'Número de dentes':'Diâmetro'} type="number" min={p.tipo==='engrenagem'?10:20} max={p.tipo==='motor'?600:240} value={p.valor} disabled={ligada} onChange={e=>{const n=Number(e.target.value);if(Number.isFinite(n))editarPeca({valor:Math.max(p.tipo==='engrenagem'?10:20,Math.min(p.tipo==='motor'?600:240,Math.round(n)))});}}/></label>}
 {p.tipo==='interruptor'&&<button className="of-botao" disabled={ligada} onClick={()=>editarPeca({nf:!p.nf})}>Contato {p.nf?'NF':'NA'} · trocar para {p.nf?'NA':'NF'}</button>}
 {p.tipo==='termico'&&<div className="of-diagnostico-peca"><strong>{p.avaria?'Contato 95–96 aberto':'Contato 95–96 fechado'}</strong>{projeto.obstrucao?<><p>Inspeção: o filtro virtual está obstruído. A causa precisa ser removida antes do rearme.</p><button className="of-botao" disabled={ligada} onClick={()=>alterar({...projeto,obstrucao:false})}>Limpar filtro virtual</button></>:<p>Ventilação livre. O comando pode ser rearmado nesta bancada virtual.</p>}<button className="of-botao" disabled={ligada||projeto.obstrucao||!p.avaria} onClick={()=>editarPeca({avaria:false})}>Rearmar F1</button></div>}
 </>:l?<><div className="of-identificacao"><b>{l.id.toUpperCase()}</b><span>{l.de.replace(':','.')} → {l.para.replace(':','.')}</span></div>{projeto.area==='mecanica'?<><label className="of-campo">Transmissão<select aria-label="Tipo de transmissão" disabled={ligada} value={l.tipo} onChange={e=>editarLigacao({tipo:e.target.value as TipoLigacao})}>{(['eixo','engrenamento','correia','cruzada'] as TipoLigacao[]).filter(t=>tipoCompativel(projeto,l.de,l.para,t)).map(t=><option key={t} value={t}>{t==='correia'?'Correia aberta':t==='cruzada'?'Correia cruzada':t==='eixo'?'Mesmo eixo':'Engrenamento externo'}</option>)}</select></label>{(l.tipo==='correia'||l.tipo==='cruzada')&&<label className="of-campo">Tensão didática <b>{l.tensao} / 100</b><input type="range" aria-label="Tensão da correia" min="0" max="100" value={l.tensao} disabled={ligada} onChange={e=>editarLigacao({tensao:Number(e.target.value)})}/><small>Escala da simulação. Em uma máquina real, a tensão depende do fabricante.</small></label>}<p>{l.tipo==='cruzada'?'A correia cruza e inverte o sentido da polia conduzida.':l.tipo==='correia'?'As duas polias giram no mesmo sentido. O diâmetro determina a relação.':l.tipo==='engrenamento'?'Duas engrenagens externas giram em sentidos contrários. Mais dentes na saída reduzem sua rotação.':'Um eixo transmite a mesma rotação e o mesmo sentido.'}</p></>:<div className="of-diagnostico-peca"><strong>{l.avaria?'Isolação danificada na articulação':'Isolação íntegra'}</strong><p>{l.avaria?'Ao mover o braço, o condutor toca o retorno 0 V. Esse caminho desvia da lâmpada e provoca o curto.':'Esta ligação conecta dois terminais. Os cruzamentos do desenho não unem fios.'}</p>{l.avaria&&<button className="of-botao" disabled={ligada} onClick={()=>editarLigacao({avaria:false})}>Recuperar isolação</button>}</div>}</>:<div className="of-selecione"><IconeOficina nome="olho" tamanho={38}/><h3>Chegue mais perto.</h3><p>Selecione uma peça ou uma ligação no desenho. A inspeção e os bornes ampliados aparecem aqui.</p></div>}
 {(p||l)&&livre&&<button className="of-botao of-perigo" disabled={ligada} onClick={remover}>Remover {p?'peça e suas ligações':'ligação'}</button>}{ligada&&(p||l)&&<p className="of-aviso-curto">Desligue a bancada antes de alterar a montagem.</p>}</section>;
}
