import type { Peca } from '../modelo/tipos';
import { CATALOGO } from '../modelo/catalogo';
import { dentes } from '../geometria';
export function PecaOficina({p,selecionada,ativa,selecionar}:{p:Peca;selecionada:boolean;ativa:boolean;selecionar:()=>void}) { const rotativa=['engrenagem','polia','rolete','motor','motor-eletrico'].includes(p.tipo);return <g transform={`translate(${p.x} ${p.y})`} className={`of-peca ${selecionada?'selecionada':''} ${ativa?'ativa':''}`} role="button" tabIndex={0} aria-label={`Selecionar ${p.tag}, ${CATALOGO[p.tipo].nome}`} data-peca={p.id} onClick={e=>{e.stopPropagation();selecionar();}} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();e.stopPropagation();selecionar();}}}>
 <rect className="of-peca-base" x="-54" y="-36" width="108" height="76" rx="12"/>
 <text className="of-tag-svg" y="-47" textAnchor="middle">{p.tag}</text>
 {p.tipo==='fonte'?<><rect x="-25" y="-22" width="50" height="43" rx="5" className="of-simbolo"/><text y="5" textAnchor="middle" className="of-valor-svg">24 V</text></>:p.tipo==='lampada'?<><circle r="23" className="of-simbolo of-lampada"/><path d="m-16-16 32 32m-32 0 32-32" className="of-simbolo"/></>:p.tipo==='bobina'?<><rect x="-25" y="-21" width="50" height="42" rx="5" className="of-simbolo of-bobina"/><path d="M-14 0h28 M0-14v28" className="of-simbolo"/></>:rotativa?<g>{p.tipo==='engrenagem'?<path d={dentes(p.valor,25)} className="of-simbolo of-roda"/>:<circle r="26" className="of-simbolo of-roda"/>}<circle r="9" className="of-simbolo"/><path d="M0-9v-16m0 34v16M9 0h16M-9 0h-16" className="of-simbolo"/>{p.tipo==='motor'&&<text y="5" textAnchor="middle" className="of-valor-svg">M</text>}</g>:<><path d="M-43 7h23m40 0h23 M-20 7 20-12" className="of-simbolo"/>{(p.nf||p.tipo==='disjuntor')&&<path d="m-6-13 14 29" className="of-simbolo"/>}{p.tipo==='termico'&&<path d="M-24-20h8v-8h9" className="of-simbolo"/>}</>}
 <text className="of-nome-svg" y="65" textAnchor="middle">{p.tipo==='engrenagem'?`${p.valor} dentes`:p.tipo==='polia'||p.tipo==='rolete'?`${p.valor} mm`:p.tipo==='motor'?`${p.valor} rpm`:p.tipo==='interruptor'?`Contato ${p.nf?'NF':'NA'}`:CATALOGO[p.tipo].nome}</text>
 </g>; }
