'use client';
import { useId } from 'react';
import { bornes,nomePorta } from '../modelo/catalogo';
import type { Eletrica, Projeto } from '../modelo/tipos';
import { PecaOficina } from './PecaOficina';
export type Ferramenta = 'inspecionar' | 'conectar' | 'medir' | 'mover';
export function posicao(p:Projeto,id:string){const [cid,b]=id.split(':'),c=p.pecas.find(c=>c.id===cid);if(!c)return {x:0,y:0};const bs=bornes(c);return {x:c.x+(bs.length===1?0:bs.indexOf(b)===0?-47:47),y:c.y+(bs.length===1?40:9)};}
export function Prancheta({projeto,eletrica,ligada,selecionado,origem,ferramenta,selecionar,terminal,mover}:{projeto:Projeto;eletrica:Eletrica;ligada:boolean;selecionado:string|null;origem:string|null;ferramenta:Ferramenta;selecionar:(id:string)=>void;terminal:(id:string)=>void;mover:(x:number,y:number)=>void}) {
 const grid=useId();return <div className="of-prancheta"><svg viewBox="0 0 620 500" aria-label="Prancheta de montagem" onClick={e=>{if(ferramenta==='mover'){const r=e.currentTarget.getBoundingClientRect();mover((e.clientX-r.left)/r.width*620,(e.clientY-r.top)/r.height*500);}}}>
 <defs><pattern id={grid} width="20" height="20" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r=".8" fill="var(--of-grid)"/></pattern></defs><rect width="620" height="500" fill={`url(#${grid})`}/>
 {projeto.ligacoes.map((l,i)=>{const a=posicao(projeto,l.de),b=posicao(projeto,l.para),ponta=(id:string)=>{const c=projeto.pecas.find(p=>p.id===id.split(':')[0]);return c&&bornes(c).indexOf(id.split(':')[1])===0?-16:16;},faixa=Math.min(477,Math.max(a.y,b.y)+85+(i%7)*11),d=`M${a.x} ${a.y}H${a.x+ponta(l.de)}V${faixa}H${b.x+ponta(l.para)}V${b.y}H${b.x}`;const v=eletrica.potenciais[l.de];return <g key={l.id} role="button" tabIndex={0} className={`of-ligacao ${selecionado===l.id?'selecionada':''} ${ligada&&(projeto.area==='mecanica'||(v??0)>1)?'ativa':''}`} aria-label={`Ligação ${nomePorta(projeto,l.de)} para ${nomePorta(projeto,l.para)}`} data-ligacao={l.id} onClick={e=>{e.stopPropagation();selecionar(l.id);}} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();selecionar(l.id);}}}><path d={d} className="of-fio-alvo"/><path d={d} className={`of-fio of-tipo-${l.tipo}`}/><circle cx={(a.x+b.x)/2} cy={faixa} r="5" className="of-no-ligacao"/></g>;})}
 {projeto.pecas.map(p=><PecaOficina key={p.id} p={p} selecionada={selecionado===p.id} ativa={ligada&&(eletrica.cargas[p.id]??0)>18} selecionar={()=>selecionar(p.id)}/>)}
 {projeto.pecas.flatMap(p=>bornes(p).map(b=>{const id=`${p.id}:${b}`,xy=posicao(projeto,id);return <g key={id} role="button" tabIndex={0} aria-label={`Terminal ${p.tag}.${b}`} data-porta={id} className={`of-porta-svg ${origem===id?'origem':''}`} onClick={e=>{e.stopPropagation();terminal(id);}} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();terminal(id);}}}><circle cx={xy.x} cy={xy.y} r="20" fill="transparent"/><circle cx={xy.x} cy={xy.y} r="7"/><text x={xy.x} y={xy.y+27} textAnchor="middle">{b}</text></g>;}))}
 {!projeto.pecas.length&&<g className="of-vazio-svg"><path d="M288 235h44m-22-22v44"/><text x="310" y="296" textAnchor="middle">Sua ideia começa com uma peça.</text><text x="310" y="322" textAnchor="middle">Abra o catálogo logo acima.</text></g>}
 </svg><div className="of-legenda"><span><i/> {projeto.area==='eletrica'?'Potencial em relação a 0 V':'Diagrama cinemático · posição livre'}</span><span>{projeto.pecas.length} peças / {projeto.ligacoes.length} ligações</span></div></div>;
}
