'use client';
import { useRef,useState } from 'react';
import type { EstadoEditor,AcaoEditor } from '@/eletrica/editor';
import { PecaDiagrama } from './PecaDiagrama';
export type ModoDiagrama='selecionar'|'sonda'|'fio'|'inserir';
export function Diagrama({editor,enviar,modo,origem,setOrigem,hover,editavel=true,destaque}:{editor:EstadoEditor;enviar:(a:AcaoEditor)=>void;modo:ModoDiagrama;origem:string|null;setOrigem:(s:string|null)=>void;hover:(s:string|null)=>void;editavel?:boolean;destaque?:string}){
  const arraste=useRef<string|null>(null),svg=useRef<SVGSVGElement>(null);
  const [ponteiro,setPonteiro]=useState<{x:number;y:number}|null>(null);
  const [fioSelecionado,setFioSelecionado]=useState<string|null>(null);
  const terminais=editor.circuito.componentes.flatMap(c=>c.terminais.map(t=>({...t,id:`${c.id}:${t.nome}`,tag:c.tag})));
  function terminal(id:string){ if(modo==='sonda'){enviar({tipo:'sondar',terminal:id});return;} if(modo==='fio'&&editavel){if(origem&&origem!==id){enviar({tipo:'editar',edicao:{tipo:'conectar',de:origem,para:id}});setOrigem(null);}else setOrigem(id);}else enviar({tipo:'selecionar',id:id.split(':')[0]});}
  const tOrigem=terminais.find(t=>t.id===origem);
  return <div className="diagrama-area"><div className="rolagem-diagrama"><svg ref={svg} viewBox="0 0 750 380" className={`diagrama-svg modo-${modo}`} aria-label="Diagrama de comando de 24 volts. Tab navega; Enter seleciona. No modo Fio, escolha dois terminais." onKeyDown={e=>{if(e.key==='Escape'){setOrigem(null);arraste.current=null;}if(e.key.startsWith('Arrow')){const itens=Array.from(e.currentTarget.querySelectorAll<SVGElement>('[tabindex="0"]'));const i=itens.indexOf(document.activeElement as SVGElement);if(i>=0){e.preventDefault();itens[(i+(e.key==='ArrowLeft'||e.key==='ArrowUp'?-1:1)+itens.length)%itens.length]?.focus();}}}} onPointerMove={e=>{if(!origem||!svg.current)return;const matrix=svg.current.getScreenCTM();if(matrix){const p=new DOMPoint(e.clientX,e.clientY).matrixTransform(matrix.inverse());setPonteiro({x:p.x,y:p.y});}}} onPointerUp={e=>{const inicio=arraste.current;if(!inicio)return;arraste.current=null;const fim=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-terminal]')?.getAttribute('data-terminal');if(modo==='fio'&&editavel&&fim&&fim!==inicio){enviar({tipo:'editar',edicao:{tipo:'conectar',de:inicio,para:fim}});setOrigem(null);}else if(fim)terminal(fim);setPonteiro(null);}} onPointerCancel={()=>{arraste.current=null;setOrigem(null);setPonteiro(null);}}>
    <text x="24" y="30" className="legenda-diagrama">COMANDO · 24 Vcc</text><text x="24" y="359" className="legenda-diagrama">0 V · RETORNO</text>
    {editor.circuito.conexoes.map(w=>{const a=terminais.find(t=>t.id===w.de),b=terminais.find(t=>t.id===w.para);if(!a||!b)return null;const via=w.via??(a.x!==b.x&&a.y!==b.y?[{x:a.x,y:b.y}]:[]);const d=`M${a.x} ${a.y} ${[...via,b].map(p=>`L${p.x} ${p.y}`).join(' ')}`;return <g key={w.id} role="button" tabIndex={0} aria-label={`Fio ${a.tag}.${a.nome} para ${b.tag}.${b.nome}`} data-fio={w.id} className={destaque===w.id?'alvo-ajuda':''} onClick={()=>{setFioSelecionado(w.id);if(modo==='inserir'&&editavel)enviar({tipo:'editar',edicao:{tipo:'inserir',conexaoId:w.id}});}} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setFioSelecionado(w.id);if(modo==='inserir'&&editavel)enviar({tipo:'editar',edicao:{tipo:'inserir',conexaoId:w.id}});}if(e.key==='Delete'&&editavel)enviar({tipo:'editar',edicao:{tipo:'desconectar',id:w.id}});}}><path d={d} className="alvo-fio"/><path d={d} className={`fio ${editor.simulacao.energizados.includes(w.id)?'energizado':''} ${fioSelecionado===w.id?'selecionado':''}`}/></g>;})}
    {editor.circuito.componentes.map(peca=><g key={peca.id} className={destaque===peca.id?'alvo-ajuda':''}><PecaDiagrama peca={peca} s={editor.simulacao} selecionada={editor.selecionado===peca.id} selecionar={()=>enviar({tipo:'selecionar',id:peca.id})} hover={hover} editavel={editavel} alternar={()=>enviar({tipo:'editar',edicao:{tipo:'contato',id:peca.id,contato:peca.contato==='NA'?'NF':'NA'}})}/></g>)}
    <g className={destaque==='selo'?'alvo-ajuda':''}><rect x="482" y="203" width="105" height="52" rx="10" className="auxiliar-fundo"/><text x="535" y="195" textAnchor="middle" className="nome-peca">Q1 · auxiliar {editor.circuito.componentes.find(c=>c.id==='q1')?.contato}</text><path d={`M500 225h15 m40 0h15 M515 225L555 ${(editor.circuito.componentes.find(c=>c.id==='q1')?.contato==='NA'?editor.simulacao.bobina:!editor.simulacao.bobina)?225:210}`} className="simbolo"/></g>
    {terminais.map(t=><g key={t.id} data-terminal={t.id} role="button" tabIndex={0} aria-label={`Terminal ${t.tag}.${t.nome}`} className={`terminal ${origem===t.id?'origem':''} ${editor.terminal===t.id?'sondado':''} ${destaque===t.id?'alvo-ajuda':''}`} onPointerDown={e=>{e.stopPropagation();arraste.current=t.id;svg.current?.setPointerCapture(e.pointerId);}} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();e.stopPropagation();terminal(t.id);}}}><circle cx={t.x} cy={t.y} r="16" className="alvo-terminal"/><circle cx={t.x} cy={t.y} r="4.5" className="pino"/><text x={t.x} y={t.y+20} textAnchor="middle" className="numero-terminal">{t.nome}</text></g>)}
    {tOrigem&&ponteiro&&<path d={`M${tOrigem.x} ${tOrigem.y}L${ponteiro.x} ${ponteiro.y}`} className="fio rascunho"/>}
  </svg></div><div className="legenda-estados"><span><i/>Energizado</span><span><i/>Sem tensão</span><span>Auxiliar Q1 acompanha a bobina</span></div>{fioSelecionado&&editavel&&<div className="acoes-fio"><span>Fio selecionado</span><button onClick={()=>{enviar({tipo:'editar',edicao:{tipo:'desconectar',id:fioSelecionado}});setFioSelecionado(null);}}>Remover fio</button><button onClick={()=>setFioSelecionado(null)}>Cancelar</button></div>}</div>;
}
