'use client';
import type { EstadoEditor,AcaoEditor } from '@/eletrica/editor';
import { medir } from '@/eletrica/simulador';
import type { ModoDiagrama } from './Diagrama';
export function Inspetor({editor,enviar,modo,terminal,editavel}:{editor:EstadoEditor;enviar:(a:AcaoEditor)=>void;modo:ModoDiagrama;terminal:(id:string)=>void;editavel:boolean}){
  const peca=editor.circuito.componentes.find(c=>c.id===editor.selecionado);
  const leitura=editor.terminal?medir(editor.simulacao,editor.terminal):null;
  return <div className="inspetor"><div className="inspetor-titulo"><strong>{peca?`${peca.tag} · ${peca.nome}`:'Conheça seu painel'}</strong><span>INSPETOR</span></div>{modo==='sonda'&&<div className="visor-sonda" aria-live="polite"><span>{editor.terminal?.replace(':','.')??'Escolha um terminal'}</span><strong>{leitura===null?'—':`${leitura} V`}</strong><small>Referência fixa: Q1.A2 · retorno 0 V{editor.terminal&&leitura===null?' · potencial indeterminado':''}</small></div>}{peca?<><p>{peca.tipo==='contatora'?'Uma bobina aciona os contatos de Q1. O auxiliar 13–14 acompanha o movimento.':peca.contato?`${peca.contato==='NA'?'Normalmente aberto: fecha':'Normalmente fechado: abre'} ao acionar.`:peca.nome}</p><div className="terminais-inspetor">{peca.terminais.map(t=><button key={t.nome} onClick={()=>terminal(`${peca.id}:${t.nome}`)}>{modo==='sonda'?'Sondar':'Terminal'} {t.nome}</button>)}</div>{editavel&&<div className="edicao-peca"><label>Tag<input key={peca.id+peca.tag} aria-label="Tag do componente" defaultValue={peca.tag} maxLength={12} onKeyDown={e=>{if(e.key==='Enter')enviar({tipo:'editar',edicao:{tipo:'tag',id:peca.id,tag:e.currentTarget.value}});}} onBlur={e=>{if(e.target.value!==peca.tag)enviar({tipo:'editar',edicao:{tipo:'tag',id:peca.id,tag:e.target.value}});}}/></label>{(peca.tipo==='botoeira'||peca.tipo==='contatora')&&<button className="botao" onClick={()=>enviar({tipo:'editar',edicao:{tipo:'contato',id:peca.id,contato:peca.contato==='NA'?'NF':'NA'}})}>Trocar para {peca.contato==='NA'?'NF':'NA'}</button>}</div>}</>:<p>Clique em uma peça no desenho. Ela também aparece na bancada ao lado.</p>}</div>;
}
