'use client';
import { useState } from 'react';
import type { EstadoEditor,AcaoEditor } from '@/eletrica/editor';
import { AbasZonas } from './AbasZonas';
import { Icone,type NomeIcone } from './Icone';
import { Diagrama,type ModoDiagrama } from './Diagrama';
import { Inspetor } from './Inspetor';
import { BornesConexao } from './BornesConexao';
const FERRAMENTAS:{id:ModoDiagrama;nome:string;icone:NomeIcone}[]=[{id:'selecionar',nome:'Selecionar',icone:'mao'},{id:'sonda',nome:'Sonda',icone:'sonda'},{id:'fio',nome:'Fio',icone:'fio'},{id:'inserir',nome:'S3 NF',icone:'mais'}];
export function PainelEletrico({editor,enviar,hover,editavel=true,destaque}:{editor:EstadoEditor;enviar:(a:AcaoEditor)=>void;hover:(s:string|null)=>void;editavel?:boolean;destaque?:string}){
  const [ferramenta,setModo]=useState<ModoDiagrama>('selecionar'),[origem,setOrigem]=useState<string|null>(null);
  const modo = ferramenta==='inserir'&&editor.circuito.componentes.some(c=>c.id==='s3')?'selecionar':ferramenta;
  function terminal(id:string){if(modo==='sonda')enviar({tipo:'sondar',terminal:id});else if(modo==='fio'&&editavel){if(origem===id)setOrigem(null);else if(origem){enviar({tipo:'editar',edicao:{tipo:'conectar',de:origem,para:id}});setOrigem(null);}else setOrigem(id);}else enviar({tipo:'selecionar',id:id.split(':')[0]});}
  return <section className="painel" aria-label="Painel de comandos"><AbasZonas/><div className="titulo-painel"><h2>Seu diagrama</h2><span>Uma conexão muda tudo.</span></div><div className="ferramentas" role="toolbar" aria-label="Ferramentas do diagrama">{FERRAMENTAS.map(f=><button key={f.id} aria-pressed={modo===f.id} disabled={(!editavel&&(f.id==='fio'||f.id==='inserir'))||(f.id==='inserir'&&editor.circuito.componentes.some(c=>c.id==='s3'))} className={`${modo===f.id?'ativa':''} ${destaque===f.id?'alvo-ajuda':''}`} onClick={()=>{setModo(f.id);setOrigem(null);}}><Icone nome={f.icone} tamanho={17}/>{f.nome}</button>)}<button title="Desfazer última edição" aria-label="Desfazer última edição" disabled={!editor.passado.length} onClick={()=>{setOrigem(null);enviar({tipo:'desfazer'});}}><Icone nome="voltar" tamanho={18}/></button></div><p className="instrucao-ferramenta" role="status">{modo==='fio'?origem?'Agora escolha o terminal de destino. Esc cancela.':'Toque em uma ponta e depois na outra. No mouse, também pode arrastar.':modo==='sonda'?'Toque em um terminal para medir em relação a A2.':modo==='inserir'?'Toque no sinal + do fio para inserir S3 em série.':'Passe pelas peças e descubra onde ficam na bancada.'}</p>{modo==='fio'&&editavel&&<BornesConexao circuito={editor.circuito} selecionado={editor.selecionado} escolherPeca={id=>enviar({tipo:'selecionar',id})} origem={origem} escolher={terminal} cancelar={()=>setOrigem(null)}/>}<Diagrama editor={editor} enviar={enviar} modo={modo} origem={origem} setOrigem={setOrigem} terminal={terminal} hover={hover} editavel={editavel} destaque={destaque}/><Inspetor editor={editor} enviar={enviar} modo={modo} editavel={editavel} terminal={terminal}/><p className="aviso-editor" role="status">{editor.aviso}</p></section>;
}
