import type { Componente,Simulacao } from '@/eletrica/tipos';
export function PecaDiagrama({peca,s,selecionada,selecionar,hover,alternar,editavel}:{peca:Componente;s:Simulacao;selecionada:boolean;selecionar:()=>void;hover:(id:string|null)=>void;alternar:()=>void;editavel:boolean}){
  if(peca.tipo==='fonte'||peca.tipo==='motor')return null;
  const acionada=peca.id==='q1'?s.bobina:peca.id==='q0'?s.entradas.disjuntorLigado:peca.id==='f1'?!s.entradas.termicoDisparado:peca.retencao?s.entradas.emergenciaTravada:s.entradas.pressionadas.includes(peca.id);
  const fechado=peca.tipo==='botoeira'||peca.tipo==='contatora' ? peca.contato==='NA'?acionada:!acionada : acionada;
  return <g className={`peca-diagrama ${selecionada?'selecionada':''}`} role="button" tabIndex={0} aria-label={`${peca.tag}, ${peca.nome}`} data-componente={peca.id} onClick={selecionar} onKeyDown={e=>{if(e.target!==e.currentTarget)return;if(e.key==='Enter'||e.key===' '){e.preventDefault();selecionar();}}} onPointerEnter={()=>hover(peca.id)} onPointerLeave={()=>hover(null)}>
    <rect className="fundo-peca" x={peca.x-39} y={peca.y-(peca.tipo==='contatora'?65:27)} width="78" height={peca.tipo==='contatora'?130:58} rx="10"/>
    {peca.tipo==='contatora'?<><path d={`M650 145v20 M650 215v20`} className="simbolo"/><rect x="627" y="165" width="46" height="50" rx="5" className={`simbolo bobina ${s.bobina?'ativa':''}`}/><text x="650" y="195" textAnchor="middle" className="texto-simbolo">Q1</text></>:peca.tipo==='lampada'?<><circle cx={peca.x} cy={peca.y} r="18" className={`simbolo ${s.lampada?'ativa':''}`}/><path d={`M${peca.x-12} ${peca.y-12}l24 24 m0-24-24 24 M${peca.x-30} ${peca.y}h12 M${peca.x+18} ${peca.y}h12`} className="simbolo"/></>:<><path d={`M${peca.x-25} ${peca.y}h10 M${peca.x+15} ${peca.y}h10 M${peca.x-15} ${peca.y} L${peca.x+15} ${peca.y-(fechado?0:17)}`} className={`simbolo ${fechado?'fechado':''}`}/>{peca.tipo==='botoeira'&&<path d={`M${peca.x} ${peca.y-18}v-9 m-9 0h18`} className="simbolo"/>}</>}
    <text x={peca.x} y={peca.y+(peca.tipo==='contatora'?-80:-43)} textAnchor="middle" className="tag-peca">{peca.tag}</text>
    <text x={peca.x} y={peca.y+(peca.tipo==='contatora'?69:peca.tipo==='lampada'?30:48)} textAnchor="middle" className="nome-peca">{peca.tipo==='botoeira'?peca.retencao?'Emergência':peca.nome:peca.tipo==='contatora'?'':peca.tipo==='termico'?'Térmico':peca.tipo==='disjuntor'?'Disjuntor':'Lâmpada'}</text>
    {peca.contato&&peca.tipo==='botoeira'&&<g role="button" tabIndex={editavel?0:-1} aria-disabled={!editavel} aria-label={`Alternar contato de ${peca.tag}, atualmente ${peca.contato}`} onClick={e=>{e.stopPropagation();if(editavel)alternar();}} onKeyDown={e=>{if(editavel&&(e.key==='Enter'||e.key===' ')){e.preventDefault();e.stopPropagation();alternar();}}}><rect x={peca.x-15} y={peca.y+56} width="30" height="23" rx="6" className="badge-contato"/><text x={peca.x} y={peca.y+72} textAnchor="middle" className="nome-peca">{peca.contato}</text></g>}
  </g>;
}
